### ISSUE TITLE
Issue with Play Protect on F-Droid

### ISSUE THREAD

**Issue by eleius** [zhanghai/TextSelectionWebSearch#4]
I tried to install this app from F-Droid but, for the first time ever, Play Protect blocked it because "Play Protect doesn't recognise this app's developer. Apps from unknown developers can sometimes be unsafe". But if I install it from Play Store it works... any idea why the F-Droid version is blocked? Maybe an [appeal](https://support.google.com/googleplay/android-developer/contact/protectappeals) request is required?

**Comment by zhanghai** [comment]
I don't think Play Protect generally works well with F-Droid, because F-Droid uses its own signature that is different from the version on Play. As a result, this is a reasonable warning from Play Protect that the signature is different and I believe as long as you know what you are doing you can just ignore it/turn it off temporarily.
